'use client'
import { OrderType } from "@/types/order";
import { useState } from 'react'
let listOrder = [
    {
        OrderId: "123456132",
        Product: {
            productId: 123,
            name: "Chậu Hình Thú",
            sku: "ZTC-1",
            slug: "ZTC-1",
            conditionDefault: 6,
            condition1: 6,
            condition2: 50,
            condition3: 100,
            condition4: 1000,
            priceDefault: 10000,
            price1: 10000,
            price2: 9000,
            price3: 8000,
            price4: 7000,
            thumbnail:
                "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
            retail: false,
            quantity: 2,
            active: false,
            selectedDelete: false,
            amount: 20000,
            unit: "Cái",
            variants: [
                {
                    name: "Chậu Hình Voi",
                    id: 72291,
                    thumbnail:
                        "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                    sku: "adw",
                    price: 10000,
                    quantity: 1,
                    vip1: 10000,
                    vip2: 9000,
                    vip3: 8000,
                    vip4: 7000,
                    selected: false,
                    variantId: 1323,
                    selectedDelete: false,
                },
                {
                    name: "Chậu Hình Cáo",
                    id: 72292,
                    thumbnail:
                        "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                    sku: "adw",
                    price: 10000,
                    quantity: 1,
                    vip1: 10000,
                    vip2: 9000,
                    vip3: 8000,
                    vip4: 7000,
                    selected: false,
                    variantId: 1236,
                    selectedDelete: false,
                },
            ],
        },
        status: "new",
        totalPrice: 10000000,
        category: [
            {
                name: "cay sen da",
                slug: "[caysenda]/con",
                condition: 1,
                amount: 1,
                products: [
                    {
                        productId: 123,
                        name: "Chậu Hình Thú",
                        sku: "ZTC-1",
                        slug: "ZTC-1",
                        conditionDefault: 6,
                        condition1: 6,
                        condition2: 50,
                        condition3: 100,
                        condition4: 1000,
                        priceDefault: 10000,
                        price1: 10000,
                        price2: 9000,
                        price3: 8000,
                        price4: 7000,
                        thumbnail:
                            "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
                        retail: false,
                        quantity: 2,
                        active: false,
                        selectedDelete: false,
                        amount: 20000,
                        unit: "Cái",
                        variants: [
                            {
                                name: "Chậu Hình Voi",
                                id: 72291,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1323,
                                selectedDelete: false,
                            },
                            {
                                name: "Chậu Hình Cáo",
                                id: 72292,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1236,
                                selectedDelete: false,
                            },
                        ],
                    },
                    {
                        productId: 123,
                        name: "Chậu Hình Thú",
                        sku: "ZTC-1",
                        slug: "ZTC-1",
                        conditionDefault: 6,
                        condition1: 6,
                        condition2: 50,
                        condition3: 100,
                        condition4: 1000,
                        priceDefault: 10000,
                        price1: 10000,
                        price2: 9000,
                        price3: 8000,
                        price4: 7000,
                        thumbnail:
                            "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
                        retail: false,
                        quantity: 2,
                        active: false,
                        selectedDelete: false,
                        amount: 20000,
                        unit: "Cái",
                        variants: [
                            {
                                name: "Chậu Hình Voi",
                                id: 72291,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1323,
                                selectedDelete: false,
                            },
                            {
                                name: "Chậu Hình Cáo",
                                id: 72292,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1236,
                                selectedDelete: false,
                            },
                        ],
                    }
                ],
                bill: 120000,
                id: 1234652
            },
            {
                name: "cay sen da",
                slug: "[caysenda]/con",
                condition: 1,
                amount: 1,
                products: [
                    {
                        productId: 123,
                        name: "Chậu Hình Thú",
                        sku: "ZTC-1",
                        slug: "ZTC-1",
                        conditionDefault: 6,
                        condition1: 6,
                        condition2: 50,
                        condition3: 100,
                        condition4: 1000,
                        priceDefault: 10000,
                        price1: 10000,
                        price2: 9000,
                        price3: 8000,
                        price4: 7000,
                        thumbnail:
                            "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
                        retail: false,
                        quantity: 2,
                        active: false,
                        selectedDelete: false,
                        amount: 20000,
                        unit: "Cái",
                        variants: [
                            {
                                name: "Chậu Hình Voi",
                                id: 72291,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1323,
                                selectedDelete: false,
                            },
                            {
                                name: "Chậu Hình Cáo",
                                id: 72292,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1236,
                                selectedDelete: false,
                            },
                        ],
                    },
                    {
                        productId: 123,
                        name: "Chậu Hình Thú",
                        sku: "ZTC-1",
                        slug: "ZTC-1",
                        conditionDefault: 6,
                        condition1: 6,
                        condition2: 50,
                        condition3: 100,
                        condition4: 1000,
                        priceDefault: 10000,
                        price1: 10000,
                        price2: 9000,
                        price3: 8000,
                        price4: 7000,
                        thumbnail:
                            "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
                        retail: false,
                        quantity: 2,
                        active: false,
                        selectedDelete: false,
                        amount: 20000,
                        unit: "Cái",
                        variants: [
                            {
                                name: "Chậu Hình Voi",
                                id: 72291,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1323,
                                selectedDelete: false,
                            },
                            {
                                name: "Chậu Hình Cáo",
                                id: 72292,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1236,
                                selectedDelete: false,
                            },
                        ],
                    },
                    {
                        productId: 123,
                        name: "Chậu Hình Thú",
                        sku: "ZTC-1",
                        slug: "ZTC-1",
                        conditionDefault: 6,
                        condition1: 6,
                        condition2: 50,
                        condition3: 100,
                        condition4: 1000,
                        priceDefault: 10000,
                        price1: 10000,
                        price2: 9000,
                        price3: 8000,
                        price4: 7000,
                        thumbnail:
                            "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
                        retail: false,
                        quantity: 2,
                        active: false,
                        selectedDelete: false,
                        amount: 20000,
                        unit: "Cái",
                        variants: [
                            {
                                name: "Chậu Hình Voi",
                                id: 72291,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1323,
                                selectedDelete: false,
                            },
                            {
                                name: "Chậu Hình Cáo",
                                id: 72292,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1236,
                                selectedDelete: false,
                            },
                        ],
                    }
                ],
                bill: 120000,
                id: 1234652
            },
            {
                name: "cay sen da",
                slug: "[caysenda]/con",
                condition: 1,
                amount: 1,
                products: [
                    {
                        productId: 123,
                        name: "Chậu Hình Thú",
                        sku: "ZTC-1",
                        slug: "ZTC-1",
                        conditionDefault: 6,
                        condition1: 6,
                        condition2: 50,
                        condition3: 100,
                        condition4: 1000,
                        priceDefault: 10000,
                        price1: 10000,
                        price2: 9000,
                        price3: 8000,
                        price4: 7000,
                        thumbnail:
                            "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
                        retail: false,
                        quantity: 2,
                        active: false,
                        selectedDelete: false,
                        amount: 20000,
                        unit: "Cái",
                        variants: [
                            {
                                name: "Chậu Hình Voi",
                                id: 72291,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1323,
                                selectedDelete: false,
                            },
                            {
                                name: "Chậu Hình Cáo",
                                id: 72292,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1236,
                                selectedDelete: false,
                            },
                        ],
                    },
                    {
                        productId: 123,
                        name: "Chậu Hình Thú",
                        sku: "ZTC-1",
                        slug: "ZTC-1",
                        conditionDefault: 6,
                        condition1: 6,
                        condition2: 50,
                        condition3: 100,
                        condition4: 1000,
                        priceDefault: 10000,
                        price1: 10000,
                        price2: 9000,
                        price3: 8000,
                        price4: 7000,
                        thumbnail:
                            "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
                        retail: false,
                        quantity: 2,
                        active: false,
                        selectedDelete: false,
                        amount: 20000,
                        unit: "Cái",
                        variants: [
                            {
                                name: "Chậu Hình Voi",
                                id: 72291,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1323,
                                selectedDelete: false,
                            },
                            {
                                name: "Chậu Hình Cáo",
                                id: 72292,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1236,
                                selectedDelete: false,
                            },
                        ],
                    }
                ],
                bill: 120000,
                id: 1234652
            }
        ]
    },
    {
        OrderId: "123456133",
        Product: {
            productId: 123,
            name: "Chậu Hình Thú",
            sku: "ZTC-1",
            slug: "ZTC-1",
            conditionDefault: 6,
            condition1: 6,
            condition2: 50,
            condition3: 100,
            condition4: 1000,
            priceDefault: 10000,
            price1: 10000,
            price2: 9000,
            price3: 8000,
            price4: 7000,
            thumbnail:
                "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
            retail: false,
            quantity: 2,
            active: false,
            selectedDelete: false,
            amount: 20000,
            unit: "Cái",
            variants: [
                {
                    name: "Chậu Hình Voi",
                    id: 72291,
                    thumbnail:
                        "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                    sku: "adw",
                    price: 10000,
                    quantity: 1,
                    vip1: 10000,
                    vip2: 9000,
                    vip3: 8000,
                    vip4: 7000,
                    selected: false,
                    variantId: 1323,
                    selectedDelete: false,
                },
                {
                    name: "Chậu Hình Cáo",
                    id: 72292,
                    thumbnail:
                        "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                    sku: "adw",
                    price: 10000,
                    quantity: 1,
                    vip1: 10000,
                    vip2: 9000,
                    vip3: 8000,
                    vip4: 7000,
                    selected: false,
                    variantId: 1236,
                    selectedDelete: false,
                },
            ],
        },
        status: "complete",
        totalPrice: 10000000,
        category: [
            {
                name: "cay sen da",
                slug: "[caysenda]/con",
                condition: 1,
                amount: 1,
                products: [
                    {
                        productId: 123,
                        name: "Chậu Hình Thú",
                        sku: "ZTC-1",
                        slug: "ZTC-1",
                        conditionDefault: 6,
                        condition1: 6,
                        condition2: 50,
                        condition3: 100,
                        condition4: 1000,
                        priceDefault: 10000,
                        price1: 10000,
                        price2: 9000,
                        price3: 8000,
                        price4: 7000,
                        thumbnail:
                            "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
                        retail: false,
                        quantity: 2,
                        active: false,
                        selectedDelete: false,
                        amount: 20000,
                        unit: "Cái",
                        variants: [
                            {
                                name: "Chậu Hình Voi",
                                id: 72291,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1323,
                                selectedDelete: false,
                            },
                            {
                                name: "Chậu Hình Cáo",
                                id: 72292,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1236,
                                selectedDelete: false,
                            },
                        ],
                    },
                    {
                        productId: 123,
                        name: "Chậu Hình Thú",
                        sku: "ZTC-1",
                        slug: "ZTC-1",
                        conditionDefault: 6,
                        condition1: 6,
                        condition2: 50,
                        condition3: 100,
                        condition4: 1000,
                        priceDefault: 10000,
                        price1: 10000,
                        price2: 9000,
                        price3: 8000,
                        price4: 7000,
                        thumbnail:
                            "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
                        retail: false,
                        quantity: 2,
                        active: false,
                        selectedDelete: false,
                        amount: 20000,
                        unit: "Cái",
                        variants: [
                            {
                                name: "Chậu Hình Voi",
                                id: 72291,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1323,
                                selectedDelete: false,
                            },
                            {
                                name: "Chậu Hình Cáo",
                                id: 72292,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1236,
                                selectedDelete: false,
                            },
                        ],
                    }
                ],
                bill: 120000,
                id: 1234652
            },
            {
                name: "cay sen da",
                slug: "[caysenda]/con",
                condition: 1,
                amount: 1,
                products: [
                    {
                        productId: 123,
                        name: "Chậu Hình Thú",
                        sku: "ZTC-1",
                        slug: "ZTC-1",
                        conditionDefault: 6,
                        condition1: 6,
                        condition2: 50,
                        condition3: 100,
                        condition4: 1000,
                        priceDefault: 10000,
                        price1: 10000,
                        price2: 9000,
                        price3: 8000,
                        price4: 7000,
                        thumbnail:
                            "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
                        retail: false,
                        quantity: 2,
                        active: false,
                        selectedDelete: false,
                        amount: 20000,
                        unit: "Cái",
                        variants: [
                            {
                                name: "Chậu Hình Voi",
                                id: 72291,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1323,
                                selectedDelete: false,
                            },
                            {
                                name: "Chậu Hình Cáo",
                                id: 72292,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1236,
                                selectedDelete: false,
                            },
                        ],
                    },
                    {
                        productId: 123,
                        name: "Chậu Hình Thú",
                        sku: "ZTC-1",
                        slug: "ZTC-1",
                        conditionDefault: 6,
                        condition1: 6,
                        condition2: 50,
                        condition3: 100,
                        condition4: 1000,
                        priceDefault: 10000,
                        price1: 10000,
                        price2: 9000,
                        price3: 8000,
                        price4: 7000,
                        thumbnail:
                            "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
                        retail: false,
                        quantity: 2,
                        active: false,
                        selectedDelete: false,
                        amount: 20000,
                        unit: "Cái",
                        variants: [
                            {
                                name: "Chậu Hình Voi",
                                id: 72291,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1323,
                                selectedDelete: false,
                            },
                            {
                                name: "Chậu Hình Cáo",
                                id: 72292,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1236,
                                selectedDelete: false,
                            },
                        ],
                    },
                    {
                        productId: 123,
                        name: "Chậu Hình Thú",
                        sku: "ZTC-1",
                        slug: "ZTC-1",
                        conditionDefault: 6,
                        condition1: 6,
                        condition2: 50,
                        condition3: 100,
                        condition4: 1000,
                        priceDefault: 10000,
                        price1: 10000,
                        price2: 9000,
                        price3: 8000,
                        price4: 7000,
                        thumbnail:
                            "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
                        retail: false,
                        quantity: 2,
                        active: false,
                        selectedDelete: false,
                        amount: 20000,
                        unit: "Cái",
                        variants: [
                            {
                                name: "Chậu Hình Voi",
                                id: 72291,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1323,
                                selectedDelete: false,
                            },
                            {
                                name: "Chậu Hình Cáo",
                                id: 72292,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1236,
                                selectedDelete: false,
                            },
                        ],
                    }
                ],
                bill: 120000,
                id: 1234652
            },
            {
                name: "cay sen da",
                slug: "[caysenda]/con",
                condition: 1,
                amount: 1,
                products: [
                    {
                        productId: 123,
                        name: "Chậu Hình Thú",
                        sku: "ZTC-1",
                        slug: "ZTC-1",
                        conditionDefault: 6,
                        condition1: 6,
                        condition2: 50,
                        condition3: 100,
                        condition4: 1000,
                        priceDefault: 10000,
                        price1: 10000,
                        price2: 9000,
                        price3: 8000,
                        price4: 7000,
                        thumbnail:
                            "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
                        retail: false,
                        quantity: 2,
                        active: false,
                        selectedDelete: false,
                        amount: 20000,
                        unit: "Cái",
                        variants: [
                            {
                                name: "Chậu Hình Voi",
                                id: 72291,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1323,
                                selectedDelete: false,
                            },
                            {
                                name: "Chậu Hình Cáo",
                                id: 72292,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1236,
                                selectedDelete: false,
                            },
                        ],
                    },
                    {
                        productId: 123,
                        name: "Chậu Hình Thú",
                        sku: "ZTC-1",
                        slug: "ZTC-1",
                        conditionDefault: 6,
                        condition1: 6,
                        condition2: 50,
                        condition3: 100,
                        condition4: 1000,
                        priceDefault: 10000,
                        price1: 10000,
                        price2: 9000,
                        price3: 8000,
                        price4: 7000,
                        thumbnail:
                            "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
                        retail: false,
                        quantity: 2,
                        active: false,
                        selectedDelete: false,
                        amount: 20000,
                        unit: "Cái",
                        variants: [
                            {
                                name: "Chậu Hình Voi",
                                id: 72291,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1323,
                                selectedDelete: false,
                            },
                            {
                                name: "Chậu Hình Cáo",
                                id: 72292,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1236,
                                selectedDelete: false,
                            },
                        ],
                    }
                ],
                bill: 120000,
                id: 1234652
            }
        ]
    },
    {
        OrderId: "123456133",
        Product: {
            productId: 123,
            name: "Chậu Hình Thú",
            sku: "ZTC-1",
            slug: "ZTC-1",
            conditionDefault: 6,
            condition1: 6,
            condition2: 50,
            condition3: 100,
            condition4: 1000,
            priceDefault: 10000,
            price1: 10000,
            price2: 9000,
            price3: 8000,
            price4: 7000,
            thumbnail:
                "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
            retail: false,
            quantity: 2,
            active: false,
            selectedDelete: false,
            amount: 20000,
            unit: "Cái",
            variants: [
                {
                    name: "Chậu Hình Voi",
                    id: 72291,
                    thumbnail:
                        "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                    sku: "adw",
                    price: 10000,
                    quantity: 1,
                    vip1: 10000,
                    vip2: 9000,
                    vip3: 8000,
                    vip4: 7000,
                    selected: false,
                    variantId: 1323,
                    selectedDelete: false,
                },
                {
                    name: "Chậu Hình Cáo",
                    id: 72292,
                    thumbnail:
                        "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                    sku: "adw",
                    price: 10000,
                    quantity: 1,
                    vip1: 10000,
                    vip2: 9000,
                    vip3: 8000,
                    vip4: 7000,
                    selected: false,
                    variantId: 1236,
                    selectedDelete: false,
                },
            ],
        },
        status: "addition",
        totalPrice: 10000000,
        category: [
            {
                name: "cay sen da",
                slug: "[caysenda]/con",
                condition: 1,
                amount: 1,
                products: [
                    {
                        productId: 123,
                        name: "Chậu Hình Thú",
                        sku: "ZTC-1",
                        slug: "ZTC-1",
                        conditionDefault: 6,
                        condition1: 6,
                        condition2: 50,
                        condition3: 100,
                        condition4: 1000,
                        priceDefault: 10000,
                        price1: 10000,
                        price2: 9000,
                        price3: 8000,
                        price4: 7000,
                        thumbnail:
                            "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
                        retail: false,
                        quantity: 2,
                        active: false,
                        selectedDelete: false,
                        amount: 20000,
                        unit: "Cái",
                        variants: [
                            {
                                name: "Chậu Hình Voi",
                                id: 72291,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1323,
                                selectedDelete: false,
                            },
                            {
                                name: "Chậu Hình Cáo",
                                id: 72292,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1236,
                                selectedDelete: false,
                            },
                        ],
                    },
                    {
                        productId: 123,
                        name: "Chậu Hình Thú",
                        sku: "ZTC-1",
                        slug: "ZTC-1",
                        conditionDefault: 6,
                        condition1: 6,
                        condition2: 50,
                        condition3: 100,
                        condition4: 1000,
                        priceDefault: 10000,
                        price1: 10000,
                        price2: 9000,
                        price3: 8000,
                        price4: 7000,
                        thumbnail:
                            "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
                        retail: false,
                        quantity: 2,
                        active: false,
                        selectedDelete: false,
                        amount: 20000,
                        unit: "Cái",
                        variants: [
                            {
                                name: "Chậu Hình Voi",
                                id: 72291,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1323,
                                selectedDelete: false,
                            },
                            {
                                name: "Chậu Hình Cáo",
                                id: 72292,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1236,
                                selectedDelete: false,
                            },
                        ],
                    }
                ],
                bill: 120000,
                id: 1234652
            },
            {
                name: "cay sen da",
                slug: "[caysenda]/con",
                condition: 1,
                amount: 1,
                products: [
                    {
                        productId: 123,
                        name: "Chậu Hình Thú",
                        sku: "ZTC-1",
                        slug: "ZTC-1",
                        conditionDefault: 6,
                        condition1: 6,
                        condition2: 50,
                        condition3: 100,
                        condition4: 1000,
                        priceDefault: 10000,
                        price1: 10000,
                        price2: 9000,
                        price3: 8000,
                        price4: 7000,
                        thumbnail:
                            "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
                        retail: false,
                        quantity: 2,
                        active: false,
                        selectedDelete: false,
                        amount: 20000,
                        unit: "Cái",
                        variants: [
                            {
                                name: "Chậu Hình Voi",
                                id: 72291,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1323,
                                selectedDelete: false,
                            },
                            {
                                name: "Chậu Hình Cáo",
                                id: 72292,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1236,
                                selectedDelete: false,
                            },
                        ],
                    },
                    {
                        productId: 123,
                        name: "Chậu Hình Thú",
                        sku: "ZTC-1",
                        slug: "ZTC-1",
                        conditionDefault: 6,
                        condition1: 6,
                        condition2: 50,
                        condition3: 100,
                        condition4: 1000,
                        priceDefault: 10000,
                        price1: 10000,
                        price2: 9000,
                        price3: 8000,
                        price4: 7000,
                        thumbnail:
                            "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
                        retail: false,
                        quantity: 2,
                        active: false,
                        selectedDelete: false,
                        amount: 20000,
                        unit: "Cái",
                        variants: [
                            {
                                name: "Chậu Hình Voi",
                                id: 72291,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1323,
                                selectedDelete: false,
                            },
                            {
                                name: "Chậu Hình Cáo",
                                id: 72292,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1236,
                                selectedDelete: false,
                            },
                        ],
                    },
                    {
                        productId: 123,
                        name: "Chậu Hình Thú",
                        sku: "ZTC-1",
                        slug: "ZTC-1",
                        conditionDefault: 6,
                        condition1: 6,
                        condition2: 50,
                        condition3: 100,
                        condition4: 1000,
                        priceDefault: 10000,
                        price1: 10000,
                        price2: 9000,
                        price3: 8000,
                        price4: 7000,
                        thumbnail:
                            "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
                        retail: false,
                        quantity: 2,
                        active: false,
                        selectedDelete: false,
                        amount: 20000,
                        unit: "Cái",
                        variants: [
                            {
                                name: "Chậu Hình Voi",
                                id: 72291,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1323,
                                selectedDelete: false,
                            },
                            {
                                name: "Chậu Hình Cáo",
                                id: 72292,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1236,
                                selectedDelete: false,
                            },
                        ],
                    }
                ],
                bill: 120000,
                id: 1234652
            },
            {
                name: "cay sen da",
                slug: "[caysenda]/con",
                condition: 1,
                amount: 1,
                products: [
                    {
                        productId: 123,
                        name: "Chậu Hình Thú",
                        sku: "ZTC-1",
                        slug: "ZTC-1",
                        conditionDefault: 6,
                        condition1: 6,
                        condition2: 50,
                        condition3: 100,
                        condition4: 1000,
                        priceDefault: 10000,
                        price1: 10000,
                        price2: 9000,
                        price3: 8000,
                        price4: 7000,
                        thumbnail:
                            "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
                        retail: false,
                        quantity: 2,
                        active: false,
                        selectedDelete: false,
                        amount: 20000,
                        unit: "Cái",
                        variants: [
                            {
                                name: "Chậu Hình Voi",
                                id: 72291,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1323,
                                selectedDelete: false,
                            },
                            {
                                name: "Chậu Hình Cáo",
                                id: 72292,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1236,
                                selectedDelete: false,
                            },
                        ],
                    },
                    {
                        productId: 123,
                        name: "Chậu Hình Thú",
                        sku: "ZTC-1",
                        slug: "ZTC-1",
                        conditionDefault: 6,
                        condition1: 6,
                        condition2: 50,
                        condition3: 100,
                        condition4: 1000,
                        priceDefault: 10000,
                        price1: 10000,
                        price2: 9000,
                        price3: 8000,
                        price4: 7000,
                        thumbnail:
                            "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
                        retail: false,
                        quantity: 2,
                        active: false,
                        selectedDelete: false,
                        amount: 20000,
                        unit: "Cái",
                        variants: [
                            {
                                name: "Chậu Hình Voi",
                                id: 72291,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1323,
                                selectedDelete: false,
                            },
                            {
                                name: "Chậu Hình Cáo",
                                id: 72292,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1236,
                                selectedDelete: false,
                            },
                        ],
                    }
                ],
                bill: 120000,
                id: 1234652
            }
        ]
    },
    {
        OrderId: "123456133",
        Product: {
            productId: 123,
            name: "Chậu Hình Thú",
            sku: "ZTC-1",
            slug: "ZTC-1",
            conditionDefault: 6,
            condition1: 6,
            condition2: 50,
            condition3: 100,
            condition4: 1000,
            priceDefault: 10000,
            price1: 10000,
            price2: 9000,
            price3: 8000,
            price4: 7000,
            thumbnail:
                "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
            retail: false,
            quantity: 2,
            active: false,
            selectedDelete: false,
            amount: 20000,
            unit: "Cái",
            variants: [
                {
                    name: "Chậu Hình Voi",
                    id: 72291,
                    thumbnail:
                        "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                    sku: "adw",
                    price: 10000,
                    quantity: 1,
                    vip1: 10000,
                    vip2: 9000,
                    vip3: 8000,
                    vip4: 7000,
                    selected: false,
                    variantId: 1323,
                    selectedDelete: false,
                },
                {
                    name: "Chậu Hình Cáo",
                    id: 72292,
                    thumbnail:
                        "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                    sku: "adw",
                    price: 10000,
                    quantity: 1,
                    vip1: 10000,
                    vip2: 9000,
                    vip3: 8000,
                    vip4: 7000,
                    selected: false,
                    variantId: 1236,
                    selectedDelete: false,
                },
            ],
        },
        status: "shipping",
        totalPrice: 10000000,
        category: [
            {
                name: "cay sen da",
                slug: "[caysenda]/con",
                condition: 1,
                amount: 1,
                products: [
                    {
                        productId: 123,
                        name: "Chậu Hình Thú",
                        sku: "ZTC-1",
                        slug: "ZTC-1",
                        conditionDefault: 6,
                        condition1: 6,
                        condition2: 50,
                        condition3: 100,
                        condition4: 1000,
                        priceDefault: 10000,
                        price1: 10000,
                        price2: 9000,
                        price3: 8000,
                        price4: 7000,
                        thumbnail:
                            "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
                        retail: false,
                        quantity: 2,
                        active: false,
                        selectedDelete: false,
                        amount: 20000,
                        unit: "Cái",
                        variants: [
                            {
                                name: "Chậu Hình Voi",
                                id: 72291,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1323,
                                selectedDelete: false,
                            },
                            {
                                name: "Chậu Hình Cáo",
                                id: 72292,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1236,
                                selectedDelete: false,
                            },
                        ],
                    },
                    {
                        productId: 123,
                        name: "Chậu Hình Thú",
                        sku: "ZTC-1",
                        slug: "ZTC-1",
                        conditionDefault: 6,
                        condition1: 6,
                        condition2: 50,
                        condition3: 100,
                        condition4: 1000,
                        priceDefault: 10000,
                        price1: 10000,
                        price2: 9000,
                        price3: 8000,
                        price4: 7000,
                        thumbnail:
                            "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
                        retail: false,
                        quantity: 2,
                        active: false,
                        selectedDelete: false,
                        amount: 20000,
                        unit: "Cái",
                        variants: [
                            {
                                name: "Chậu Hình Voi",
                                id: 72291,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1323,
                                selectedDelete: false,
                            },
                            {
                                name: "Chậu Hình Cáo",
                                id: 72292,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1236,
                                selectedDelete: false,
                            },
                        ],
                    }
                ],
                bill: 120000,
                id: 1234652
            },
            {
                name: "cay sen da",
                slug: "[caysenda]/con",
                condition: 1,
                amount: 1,
                products: [
                    {
                        productId: 123,
                        name: "Chậu Hình Thú",
                        sku: "ZTC-1",
                        slug: "ZTC-1",
                        conditionDefault: 6,
                        condition1: 6,
                        condition2: 50,
                        condition3: 100,
                        condition4: 1000,
                        priceDefault: 10000,
                        price1: 10000,
                        price2: 9000,
                        price3: 8000,
                        price4: 7000,
                        thumbnail:
                            "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
                        retail: false,
                        quantity: 2,
                        active: false,
                        selectedDelete: false,
                        amount: 20000,
                        unit: "Cái",
                        variants: [
                            {
                                name: "Chậu Hình Voi",
                                id: 72291,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1323,
                                selectedDelete: false,
                            },
                            {
                                name: "Chậu Hình Cáo",
                                id: 72292,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1236,
                                selectedDelete: false,
                            },
                        ],
                    },
                    {
                        productId: 123,
                        name: "Chậu Hình Thú",
                        sku: "ZTC-1",
                        slug: "ZTC-1",
                        conditionDefault: 6,
                        condition1: 6,
                        condition2: 50,
                        condition3: 100,
                        condition4: 1000,
                        priceDefault: 10000,
                        price1: 10000,
                        price2: 9000,
                        price3: 8000,
                        price4: 7000,
                        thumbnail:
                            "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
                        retail: false,
                        quantity: 2,
                        active: false,
                        selectedDelete: false,
                        amount: 20000,
                        unit: "Cái",
                        variants: [
                            {
                                name: "Chậu Hình Voi",
                                id: 72291,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1323,
                                selectedDelete: false,
                            },
                            {
                                name: "Chậu Hình Cáo",
                                id: 72292,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1236,
                                selectedDelete: false,
                            },
                        ],
                    },
                    {
                        productId: 123,
                        name: "Chậu Hình Thú",
                        sku: "ZTC-1",
                        slug: "ZTC-1",
                        conditionDefault: 6,
                        condition1: 6,
                        condition2: 50,
                        condition3: 100,
                        condition4: 1000,
                        priceDefault: 10000,
                        price1: 10000,
                        price2: 9000,
                        price3: 8000,
                        price4: 7000,
                        thumbnail:
                            "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
                        retail: false,
                        quantity: 2,
                        active: false,
                        selectedDelete: false,
                        amount: 20000,
                        unit: "Cái",
                        variants: [
                            {
                                name: "Chậu Hình Voi",
                                id: 72291,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1323,
                                selectedDelete: false,
                            },
                            {
                                name: "Chậu Hình Cáo",
                                id: 72292,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1236,
                                selectedDelete: false,
                            },
                        ],
                    }
                ],
                bill: 120000,
                id: 1234652
            },
            {
                name: "cay sen da",
                slug: "[caysenda]/con",
                condition: 1,
                amount: 1,
                products: [
                    {
                        productId: 123,
                        name: "Chậu Hình Thú",
                        sku: "ZTC-1",
                        slug: "ZTC-1",
                        conditionDefault: 6,
                        condition1: 6,
                        condition2: 50,
                        condition3: 100,
                        condition4: 1000,
                        priceDefault: 10000,
                        price1: 10000,
                        price2: 9000,
                        price3: 8000,
                        price4: 7000,
                        thumbnail:
                            "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
                        retail: false,
                        quantity: 2,
                        active: false,
                        selectedDelete: false,
                        amount: 20000,
                        unit: "Cái",
                        variants: [
                            {
                                name: "Chậu Hình Voi",
                                id: 72291,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1323,
                                selectedDelete: false,
                            },
                            {
                                name: "Chậu Hình Cáo",
                                id: 72292,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1236,
                                selectedDelete: false,
                            },
                        ],
                    },
                    {
                        productId: 123,
                        name: "Chậu Hình Thú",
                        sku: "ZTC-1",
                        slug: "ZTC-1",
                        conditionDefault: 6,
                        condition1: 6,
                        condition2: 50,
                        condition3: 100,
                        condition4: 1000,
                        priceDefault: 10000,
                        price1: 10000,
                        price2: 9000,
                        price3: 8000,
                        price4: 7000,
                        thumbnail:
                            "https://caysenda.vn/resources/upload/17892827873_102253868.jpg",
                        retail: false,
                        quantity: 2,
                        active: false,
                        selectedDelete: false,
                        amount: 20000,
                        unit: "Cái",
                        variants: [
                            {
                                name: "Chậu Hình Voi",
                                id: 72291,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1323,
                                selectedDelete: false,
                            },
                            {
                                name: "Chậu Hình Cáo",
                                id: 72292,
                                thumbnail:
                                    "https://caysenda.vn/resources/upload/22216875771_102253868.jpg",
                                sku: "adw",
                                price: 10000,
                                quantity: 1,
                                vip1: 10000,
                                vip2: 9000,
                                vip3: 8000,
                                vip4: 7000,
                                selected: false,
                                variantId: 1236,
                                selectedDelete: false,
                            },
                        ],
                    }
                ],
                bill: 120000,
                id: 1234652
            }
        ]
    }
]

// Create a function to get orders
const getOrder = async (status?: string) => {

    if (status === undefined) {
        return listOrder;
    } else {
        return listOrder.filter((order) => order.status === status) as unknown as OrderType[];
    }
};

// Create a function to delete orders 
const delOrder = async (orderId: string) => {
    listOrder = listOrder.filter((order) => order.OrderId !== orderId);

};

// Create a function to update orders
const updateOrder = async (_Order : any) => {
    const index = listOrder.findIndex((o) => o.OrderId === _Order.OrderId);
}
const detailOrder = async (orderId: string) => {
    return listOrder.find((order)=> {order.OrderId === orderId});
}
// Export the functions
const OrderService = { getOrder, delOrder, updateOrder }
export default OrderService;
